### ISSUE TITLE
Issue with initializing a database from clean install 

### ISSUE THREAD

**Issue by myco-bradshaw** [xonq/mycotools#5] opened 2024-10-24 15:14 UTC
Hello, I have been having issues downloading and creating an initial mycotoolsdb. I have created a conda environment and followed all the steps to install and update mycotools.

I then run this command:
mtdb update -i /path/to/mycotoolsDB/mycotools_agaricomycotina_10_2024/ --lineage "Agaricomycotina" --rank "subphylum"

I can enter my JGI and NCBI credentials and then the process begins downloads. However, I always get this error after: Is it an issue with the pandas package? Also is there a way to save downloaded genomes and gff files through the command line?

Assimilating MycoCosm (1 download/minute)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  257k    0  257k    0     0   576k      0 --:--:-- --:--:-- --:--:--  577k
Traceback (most recent call last):
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 343, in dwnld_mycocosm
    jgi_df = pd.read_csv(out_file, encoding = 'cp1252')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 574, in pandas._libs.parsers.TextReader.__cinit__
  File "parsers.pyx", line 663, in pandas._libs.parsers.TextReader._get_header
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2053, in pandas._libs.parsers.raise_parser_error
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 234838: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "parsers.pyx", line 1120, in pandas._libs.parsers.TextReader._convert_tokens
  File "parsers.pyx", line 1272, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "parsers.pyx", line 1285, in pandas._libs.parsers.TextReader._string_convert
  File "parsers.pyx", line 1535, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 8: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/abradshaw/miniconda3/envs/mycotools/bin/update_mtdb", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 1752, in cli
    main()
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 1741, in main
    control_flow(args.init, args.update, args.reference, args.add, args.taxonomy,
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 1621, in control_flow
    new_mtdb, update_mtdb = rogue_update(
                            ^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 956, in rogue_update
    jgi_df = dwnld_mycocosm(mycocosm_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/mycotools/update_mtdb.py", line 345, in dwnld_mycocosm
    jgi_df = pd.read_csv(out_file, encoding = 'utf-8')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abradshaw/miniconda3/envs/mycotools/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 921, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 1066, in pandas._libs.parsers.TextReader._convert_column_data
  File "parsers.pyx", line 1127, in pandas._libs.parsers.TextReader._convert_tokens
  File "parsers.pyx", line 1272, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "parsers.pyx", line 1285, in pandas._libs.parsers.TextReader._string_convert
  File "parsers.pyx", line 1535, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 8: invalid continuation byte

**Comment by xonq** [comment] 2024-10-24 15:28
This looks like Pandas is having trouble reading the JGI table. Can you upload the file - it should be in `...mycotoolsDB/mycotools_agaricomycotina_10_2024/mycotoolsdb/log/202410<DD>/202410<DD>.mycocosm.csv`?

Thanks.

Yes, you can save individual genomes using `ncbiDwnld` or `jgiDwnld` scripts

**Comment by xonq** [comment] 2024-10-24 15:40
I'm able to reproduce this issue, it looks like JGI's table has changed their text encoding and the two ones I'm attempting here don't work. I'll need to see if I can identify their new encoding and incorporate a fix.

**Comment by myco-bradshaw** [comment] 2024-10-24 15:43
[20241024.mycocosm.csv](https://github.com/user-attachments/files/17509460/20241024.mycocosm.csv)

Thank you for looking into this so quickly, attached is the csv file

**Comment by xonq** [comment] 2024-10-24 16:03
no problem, I'm guessing someone new or some different software generated the JGI table. I've fixed the issue, hopefully future-proofed it from this again, and tested the resolution on my end. 

The conda package update will be available when they accept it this afternoon. If you would like to update via pypi, please run `python3 -m pip install mycotools --upgrade` in your mycotools conda environment and you should be able to access v0.32.4 immediately. I will close this issue and if you continue to run into this error let me know.

**Closed by xonq** 2024-10-24 16:03 UTC
